
# ************ Compilación Ejercicios ************
Ejercicio1:
	g++ -std=c++11 -pthread -I. -o Ejercicio1 Ejercicio1.cpp scd.cpp

Ejercicio2:
	g++ -std=c++11 -pthread -I. -o Ejercicio2 Ejercicio2.cpp scd.cpp

Ejercicio3:
	g++ -std=c++11 -pthread -I. -o Ejercicio3 Ejercicio3.cpp scd.cpp

Ejercicio4:
	g++ -std=c++11 -pthread -I. -o Ejercicio4 Ejercicio4.cpp scd.cpp

Ejercicio5:
	g++ -std=c++11 -pthread -I. -o Ejercicio5 Ejercicio5.cpp scd.cpp

Ejercicio6:
	g++ -std=c++11 -pthread -I. -o Ejercicio6 Ejercicio6.cpp scd.cpp

Ejercicio7:
	g++ -std=c++11 -pthread -I. -o Ejercicio7 Ejercicio7.cpp scd.cpp

Ejercicio8:
	g++ -std=c++11 -pthread -I. -o Ejercicio8 Ejercicio8.cpp scd.cpp

Ejercicio9:
	g++ -std=c++11 -pthread -I. -o Ejercicio9 Ejercicio9.cpp scd.cpp

Ejemplo:
	g++ -std=c++11 -pthread -I. -o ejemplo ejemplo.cpp scd.cpp

# ************ Compilación Practicas ************
Practica1:
	g++ -std=c++11 -pthread -I. -o Practica1 Practica1.cpp scd.cpp

Practica2:
	g++ -std=c++11 -pthread -I. -o Practica2 Practica2.cpp scd.cpp



# ************ Compila ************

CEjercicio3:
	g++ -std=c++11 -pthread -I. -o Ejercicio3 Ejercicio3.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio3

CEjercicio4:
	g++ -std=c++11 -pthread -I. -o Ejercicio4 Ejercicio4.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio4

CEjercicio5:
	g++ -std=c++11 -pthread -I. -o Ejercicio5 Ejercicio5.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio5

CEjercicio6:
	g++ -std=c++11 -pthread -I. -o Ejercicio6 Ejercicio6.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio6

CEjercicio7:
	g++ -std=c++11 -pthread -I. -o Ejercicio7 Ejercicio7.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio7


CEjercicio8:
	g++ -std=c++11 -pthread -I. -o Ejercicio8 Ejercicio8.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio8

CEjercicio9:
	g++ -std=c++11 -pthread -I. -o Ejercicio9 Ejercicio9.cpp scd.cpp
	@echo "Correcto, Limpio ..."
	@rm Ejercicio9

# ************ Limpieza ************
clean :
	@echo "Limpiando Ejercicios..."
	@rm Ejercicio1 Ejercicio2 Ejercicio3 Ejercicio4 Ejercicio5 Ejercicio6 Ejercicio7 Ejercicio8 Ejercicio9
	@echo "Archivos borrados con exito"
	

cleanp:

	@echo "Limpiando Practicas..."
	@rm Practica1 Practica2
	@echo "Archivos borrados con exito"

autor:
	@echo "Torres Ramos, Juan Luis"