
# ************ Compilación y Ejecuta ************

Ejemplo:
	mpicxx -std=c++11 -o Ejemplo Ejemplo.cpp 
	mpirun  -oversubscribe -np 4 ./Ejemplo

Ejercicio1:
	mpicxx -std=c++11 -o Ejercicio1 Ejercicio1.cpp 
	mpirun -np 4 ./Ejercicio1

Ejercicio2:
	mpicxx -std=c++11 -o Ejercicio2 Ejercicio2.cpp
	mpirun -np 2 ./Ejercicio2

Ejercicio3:
	mpicxx -std=c++11 -o Ejercicio3 Ejercicio3.cpp
	mpirun -np 4 ./Ejercicio3

Ejercicio4:
	mpicxx -std=c++11 -o Ejercicio4 Ejercicio4.cpp
	mpirun -np 6 ./Ejercicio4

Ejercicio5:
	mpicxx -std=c++11 -o Ejercicio5 Ejercicio5.cpp
	mpirun -np 6 ./Ejercicio5

Ejercicio6:
	mpicxx -std=c++11 -o Ejercicio6 Ejercicio6.cpp
	mpirun -np 6 ./Ejercicio6

Ejercicio7:
	mpicxx	-std=c++11 -I. -o Ejercicio7 Ejercicio7.cpp scd.cpp
	mpirun -np 8 ./Ejercicio7

Ejercicio8:
	mpicxx -std=c++11 -o Ejercicio8 Ejercicio8.cpp
	mpirun -oversubscribe -np 10 ./Ejercicio8
	

# ************ Practicas ************

Practica1:
	mpicxx -std=c++11 -o Practica1 Practica1.cpp
	mpirun -oversubscribe -np 3 ./Practica1

Practica2:
	mpicxx -std=c++11 -o Practica2 Practica2.cpp
	mpirun -oversubscribe -np 3 ./Practica2

Practica3:
	mpicxx -std=c++11 -o Practica3 Practica3.cpp
	mpirun -oversubscribe -np 10 ./Practica3

Practica4:
	mpicxx -std=c++11 -o Practica4 Practica4.cpp
	mpirun -oversubscribe -np 10 ./Practica4

Practica5:
	mpicxx -std=c++11 -o Practica5 Practica5.cpp
	mpirun -oversubscribe -np 11 ./Practica5
# ************ Compila ************

CEjercicio1:
	mpicxx -std=c++11 -o Ejercicio1 Ejercicio1.cpp
	@echo "Compila, limpio ..."
	@rm Ejercicio1

CEjercicio2:
	mpicxx -std=c++11 -o Ejercicio2 Ejercicio2.cpp
	@echo "Compila, limpio ..."
	@rm Ejercicio2

CEjercicio3:
	mpicxx -std=c++11 -o Ejercicio3 Ejercicio3.cpp
	@echo "Compila, limpio ..."
	@rm Ejercicio3

# ************ Limpieza ************
clean :
	@echo "Limpiando Ejercicios..."
	@rm Ejercicio1 Ejercicio2 Ejercicio3 Ejercicio4 Ejercicio5 Ejercicio6 Ejercicio7 Ejercicio8 Ejercicio9
	@echo "Archivos borrados con exito"
	

cleanp:

	@echo "Limpiando Practicas..."
	@rm Practica1 Practica2 Practica3 Practica4 Practica5
	@echo "Archivos borrados con exito"

autor:
	@echo "Torres Ramos, Juan Luis"