
# ************ Compilación Ejercicios ************
Ejercicio1:
	g++ -std=c++11 -pthread -o Ejercicio1 Ejercicio1.cpp 

Ejercicio2:
	g++ -std=c++11 -pthread -o Ejercicio2 Ejercicio2.cpp

Ejercicio3:
	g++ -std=c++11 -pthread -o Ejercicio3 Ejercicio3.cpp

Ejercicio4:
	g++ -std=c++11 -pthread -o Ejercicio4 Ejercicio4.cpp

Ejercicio5:
	g++ -std=c++11 -pthread -o Ejercicio5 Ejercicio5.cpp

Ejercicio6:
	g++ -std=c++11 -pthread -o Ejercicio6 Ejercicio6.cpp

Ejercicio7:
	g++ -std=c++11 -pthread -o Ejercicio7 Ejercicio7.cpp

Ejercicio8:
	g++ -std=c++11 -pthread -o Ejercicio8 Ejercicio8.cpp

Ejercicio9:
	g++ -std=c++11 -pthread -o Ejercicio9 Ejercicio9.cpp

Ejercicio10:
	g++ -std=c++11 -pthread -o Ejercicio10 Ejercicio10.cpp

Ejercicio11:
	g++ -std=c++11 -pthread -o Ejercicio11 Ejercicio11.cpp

Ejercicio12:
	g++ -std=c++11 -pthread -I. -o Ejercicio12 Ejercicio12.cpp scd.cpp

# ************ Compilación Practicas ************

Practica0:
	g++ -std=c++11 -pthread -I. -o Practica0 Practica0.cpp scd.cpp

Practica1:
	g++ -std=c++11 -pthread -I. -o Practica1 Practica1.cpp scd.cpp

Practica2:
	g++ -std=c++11 -pthread -I. -o Practica2 Practica2.cpp scd.cpp

# ************ Limpieza ************
clean :
	@echo "Limpiando Ejercicios..."
	@rm Ejercicio1 Ejercicio2 Ejercicio3 Ejercicio4 Ejercicio5 Ejercicio6 Ejercicio7 Ejercicio8 Ejercicio9 Ejercicio10 Ejercicio11 Ejercicio12

	@echo "Archivos borrados con exito"

cleanp:

	@echo "Limpiando Practicas..."
	@rm Practica0 Practica1 Practica2
	@echo "Archivos borrados con exito"

autor:
	@echo "Torres Ramos, Juan Luis"